### ISSUE TITLE
Feature extractor with VGG-16

### ISSUE THREAD

**Issue by ustundag** [ChiWeiHsiao/SphereNet-pytorch#5]
Hi, Thank you very much for your great effort!

I just want to extract features from a panoramic image, not for object detection.

In the paper for the object detection part, it says that "As feature extractor, all models use a VGG-16 network". So, should I construct VGG-16 network by changing normal conv/pool layers with spherical_conv/pool layers?

Thanks in advance!

**Comment by ChiWeiHsiao** [comment]
Yes, you're right.

**Comment by ustundag** [comment]
Thanks again. But one more question.

Should the input shape be in the ratio [1:1] as in VGG16? I want to feed my spherical_VGG16 model with panoramic images which are in the ratio [2:1]. Do I have to resize panoramic inputs to the ratio [1:1]?

**Comment by ChiWeiHsiao** [comment]
The author seemed to use ratio [2:1].
In section 4.2, ```The scenes are rendered using an equirectangular projection to images of dimension 512 × 256```.

**Comment by ustundag** [comment]
Thanks for your attention! Sorry to have missed that info.
